# Housing Rental Analysis for San Francisco

In this challenge, your job is to use your data visualization skills, including aggregation, interactive visualizations, and geospatial analysis, to find properties in the San Francisco market that are viable investment opportunities.

## Instructions

Use the `san_francisco_housing.ipynb` notebook to visualize and analyze the real-estate data.

Note that this assignment requires you to create a visualization by using hvPlot and GeoViews. Additionally, you need to read the `sfo_neighborhoods_census_data.csv` file from the `Resources` folder into the notebook and create the DataFrame that you’ll use in the analysis.

The main task in this Challenge is to visualize and analyze the real-estate data in your Jupyter notebook. Use the `san_francisco_housing.ipynb` notebook to complete the following tasks:

* Calculate and plot the housing units per year.

* Calculate and plot the average prices per square foot.

* Compare the average prices by neighborhood.

* Build an interactive neighborhood map.

* Compose your data story.

### Calculate and Plot the Housing Units per Year

For this part of the assignment, use numerical and visual aggregation to calculate the number of housing units per year, and then visualize the results as a bar chart. To do so, complete the following steps:

1. Use the `groupby` function to group the data by year. Aggregate the results by the `mean` of the groups.

2. Use the `hvplot` function to plot the `housing_units_by_year` DataFrame as a bar chart. Make the x-axis represent the `year` and the y-axis represent the `housing_units`.

3. Style and format the line plot to ensure a professionally styled visualization.

4. Note that your resulting plot should appear similar to the following image:

![A screenshot depicts an example of the resulting bar chart.](Images/zoomed-housing-units-by-year.png)

5. Answer the following question:

    * What’s the overall trend in housing units over the period that you’re analyzing?

### Calculate and Plot the Average Sale Prices per Square Foot

For this part of the assignment, use numerical and visual aggregation to calculate the average prices per square foot, and then visualize the results as a bar chart. To do so, complete the following steps:

1. Group the data by year, and then average the results. What’s the lowest gross rent that’s reported for the years that the DataFrame includes?

2. Create a new DataFrame named `prices_square_foot_by_year` by filtering out the “housing_units” column. The new DataFrame should include the averages per year for only the sale price per square foot and the gross rent.

3. Use hvPlot to plot the `prices_square_foot_by_year` DataFrame as a line plot.

    > **Hint** This single plot will include lines for both `sale_price_sqr_foot` and `gross_rent`.

4. Style and format the line plot to ensure a professionally styled visualization.

5. Note that your resulting plot should appear similar to the following image:

![A screenshot depicts an example of the resulting plot.](Images/avg-sale-px-sq-foot-gross-rent.png)

6. Use both the `prices_square_foot_by_year` DataFrame and interactive plots to answer the following questions:

    * Did any year experience a drop in the average sale price per square foot compared to the previous year?

    * If so, did the gross rent increase or decrease during that year?

### Compare the Average Sale Prices by Neighborhood

For this part of the assignment, use interactive visualizations and widgets to explore the average sale price per square foot by neighborhood. To do so, complete the following steps:

1. Create a new DataFrame that groups the original DataFrame by year and neighborhood. Aggregate the results by the `mean` of the groups.

2. Filter out the “housing_units” column to create a DataFrame that includes only the `sale_price_sqr_foot` and `gross_rent` averages per year.

3. Create an interactive line plot with hvPlot that visualizes both `sale_price_sqr_foot` and `gross_rent`. Set the x-axis parameter to the year (`x="year"`). Use the `groupby` parameter to create an interactive widget for `neighborhood`.

4. Style and format the line plot to ensure a professionally styled visualization.

5. Note that your resulting plot should appear similar to the following image:

![A screenshot depicts an example of the resulting plot.](Images/pricing-info-by-neighborhood.png)

6. Use the interactive visualization to answer the following question:

    * For the Anza Vista neighborhood, is the average sale price per square foot for 2016 more or less than the price that’s listed for 2012? 

### Build an Interactive Neighborhood Map

For this part of the assignment, explore the geospatial relationships in the data by using interactive visualizations with hvPlot and GeoViews. To build your map, use the `sfo_data_df` DataFrame (created during the initial import), which includes the neighborhood location data with the average prices. To do all this, complete the following steps:

1. Read the `neighborhood_coordinates.csv` file from the `Resources` folder into the notebook, and create a DataFrame named `neighborhood_locations_df`. Be sure to set the `index_col` of the DataFrame as “Neighborhood”.

2. Using the original `sfo_data_df` Dataframe, create a DataFrame named `all_neighborhood_info_df` that groups the data by neighborhood. Aggregate the results by the `mean` of the group.

3. Review the two code cells that concatenate the `neighborhood_locations_df` DataFrame with the `all_neighborhood_info_df` DataFrame. Note that the first cell uses the [Pandas concat function](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.concat.html) to create a DataFrame named `all_neighborhoods_df`. The second cell cleans the data and sets the “Neighborhood” column. Be sure to run these cells to create the `all_neighborhoods_df` DataFrame, which you’ll need to create the geospatial visualization.

4. Using hvPlot with GeoViews enabled, create a `points` plot for the `all_neighborhoods_df` DataFrame. Be sure to do the following:

    * Set the `geo` parameter to True.
    * Set the `size` parameter to “sale_price_sqr_foot”.
    * Set the `color` parameter to “gross_rent”.
    * Set the `frame_width` parameter to 700.
    * Set the `frame_height` parameter to 500.
    * Include a descriptive title.

Note that your resulting plot should appear similar to the following image:

![A screenshot depicts an example of a scatter plot created with hvPlot and GeoViews.](Images/6-4-geoviews-plot.png)

5. Use the interactive map to answer the following question:

    * Which neighborhood has the highest gross rent, and which has the highest sale price per square foot?

### Compose Your Data Story

Based on the visualizations that you created, answer the following questions:

* How does the trend in rental income growth compare to the trend in sales prices? Does this same trend hold true for all the neighborhoods across San Francisco?

* What insights can you share with your company about the potential one-click, buy-and-rent strategy that they're pursuing? Do neighborhoods exist that you would suggest for investment, and why?

In [55]:
# Import the required libraries and dependencies
import pandas as pd
import hvplot.pandas
from pathlib import Path

## Import the data 

In [56]:
# Using the read_csv function and Path module, create a DataFrame 
# by importing the sfo_neighborhoods_census_data.csv file from the Resources folder
sfo_data_df = pd.read_csv(Path("./Resources/sfo_neighborhoods_census_data.csv"))

# Review the first and last five rows of the DataFrame
display (sfo_data_df.head())
display (sfo_data_df.tail())

year      neighborhood  sale_price_sqr_foot  housing_units  gross_rent
0  2010      Alamo Square           291.182945         372560        1239
1  2010        Anza Vista           267.932583         372560        1239
2  2010           Bayview           170.098665         372560        1239
3  2010  Buena Vista Park           347.394919         372560        1239
4  2010  Central Richmond           319.027623         372560        1239

year            neighborhood  sale_price_sqr_foot  housing_units  \
392  2016          Telegraph Hill           903.049771         384242   
393  2016              Twin Peaks           970.085470         384242   
394  2016  Van Ness/ Civic Center           552.602567         384242   
395  2016       Visitacion Valley           328.319007         384242   
396  2016           Westwood Park           631.195426         384242   

     gross_rent  
392        4390  
393        4390  
394        4390  
395        4390  
396        4390

---

## Calculate and Plot the Housing Units per Year

For this part of the assignment, use numerical and visual aggregation to calculate the number of housing units per year, and then visualize the results as a bar chart. To do so, complete the following steps:

1. Use the `groupby` function to group the data by year. Aggregate the results by the `mean` of the groups.

2. Use the `hvplot` function to plot the `housing_units_by_year` DataFrame as a bar chart. Make the x-axis represent the `year` and the y-axis represent the `housing_units`.

3. Style and format the line plot to ensure a professionally styled visualization.

4. Note that your resulting plot should appear similar to the following image:

![A screenshot depicts an example of the resulting bar chart.](Images/zoomed-housing-units-by-year.png)

5. Answer the following question:

    * What’s the overall trend in housing units over the period that you’re analyzing?



### Step 1: Use the `groupby` function to group the data by year. Aggregate the results by the `mean` of the groups.

In [57]:
# Create a numerical aggregation that groups the data by the year and then averages the results.
housing_units_by_year = sfo_data_df.groupby("year").mean()

# Review the DataFrame
housing_units_by_year

sale_price_sqr_foot  housing_units  gross_rent
year                                                
2010           369.344353       372560.0      1239.0
2011           341.903429       374507.0      1530.0
2012           399.389968       376454.0      2324.0
2013           483.600304       378401.0      2971.0
2014           556.277273       380348.0      3528.0
2015           632.540352       382295.0      3739.0
2016           697.643709       384242.0      4390.0

### Step 2: Use the `hvplot` function to plot the `housing_units_by_year` DataFrame as a bar chart. Make the x-axis represent the `year` and the y-axis represent the `housing_units`.

### Step 3: Style and format the line plot to ensure a professionally styled visualization.

In [58]:
# Create a visual aggregation explore the housing units by year
housing_units_by_year.hvplot.bar(x= "year",
                                 y= "housing_units",
                                 label= "Housing units in San Francisco from 2010 to 2016",
                                 rot= 45,
                                 ylim= (365000, 385000)
                                ).opts(yformatter='%.0f',
                                      color="blue")

:Bars   [year]   (housing_units)

### Step 5: Answer the following question:

**Question:** What is the overall trend in housing_units over the period being analyzed?

**Answer:** # Overall, we are observing a consistent uptrend, the housing Units are growing over the period being analyzed 

---

## Calculate and Plot the Average Sale Prices per Square Foot

For this part of the assignment, use numerical and visual aggregation to calculate the average prices per square foot, and then visualize the results as a bar chart. To do so, complete the following steps:

1. Group the data by year, and then average the results. What’s the lowest gross rent that’s reported for the years that the DataFrame includes?

2. Create a new DataFrame named `prices_square_foot_by_year` by filtering out the “housing_units” column. The new DataFrame should include the averages per year for only the sale price per square foot and the gross rent.

3. Use hvPlot to plot the `prices_square_foot_by_year` DataFrame as a line plot.

    > **Hint** This single plot will include lines for both `sale_price_sqr_foot` and `gross_rent`.

4. Style and format the line plot to ensure a professionally styled visualization.

5. Note that your resulting plot should appear similar to the following image:

![A screenshot depicts an example of the resulting plot.](Images/avg-sale-px-sq-foot-gross-rent.png)

6. Use both the `prices_square_foot_by_year` DataFrame and interactive plots to answer the following questions:

    * Did any year experience a drop in the average sale price per square foot compared to the previous year?

    * If so, did the gross rent increase or decrease during that year?



### Step 1: Group the data by year, and then average the results.

In [61]:
# Create a numerical aggregation by grouping the data by year and averaging the results
housing_units_by_year = sfo_data_df.groupby("year").mean()

# Review the resulting DataFrame
housing_units_by_year

sale_price_sqr_foot  housing_units  gross_rent
year                                                
2010           369.344353       372560.0      1239.0
2011           341.903429       374507.0      1530.0
2012           399.389968       376454.0      2324.0
2013           483.600304       378401.0      2971.0
2014           556.277273       380348.0      3528.0
2015           632.540352       382295.0      3739.0
2016           697.643709       384242.0      4390.0

**Question:** What is the lowest gross rent reported for the years included in the DataFrame?

**Answer:** # The lowest rent reported for the year is 1239.0 in 2010

### Step 2: Create a new DataFrame named `prices_square_foot_by_year` by filtering out the “housing_units” column. The new DataFrame should include the averages per year for only the sale price per square foot and the gross rent.

In [62]:
# Filter out the housing_units column, creating a new DataFrame 
prices_square_foot_by_year = sfo_data_df.drop(columns=["housing_units"])

# Keep only sale_price_sqr_foot and gross_rent averages per year
prices_square_foot_by_year = prices_square_foot_by_year.groupby("year").mean()

# Review the DataFrame
prices_square_foot_by_year

sale_price_sqr_foot  gross_rent
year                                 
2010           369.344353      1239.0
2011           341.903429      1530.0
2012           399.389968      2324.0
2013           483.600304      2971.0
2014           556.277273      3528.0
2015           632.540352      3739.0
2016           697.643709      4390.0

### Step 3: Use hvPlot to plot the `prices_square_foot_by_year` DataFrame as a line plot.

> **Hint** This single plot will include lines for both `sale_price_sqr_foot` and `gross_rent`

### Step 4: Style and format the line plot to ensure a professionally styled visualization.


In [63]:
# Plot prices_square_foot_by_year. 
# Inclued labels for the x- and y-axes, and a title.
prices_square_foot_by_year.hvplot(x ='year',
                                  y = ['sale_price_sqr_foot','gross_rent'],
                                  value_label='Gross Rent/Sale Price Per Square Foot',
                                  title='Sale Price per Square Foot and Average Gross Rent - 2010-2016 - San Francisco'
                                 )

:NdOverlay   [Variable]
   :Curve   [year]   (Gross Rent/Sale Price Per Square Foot)

### Step 6: Use both the `prices_square_foot_by_year` DataFrame and interactive plots to answer the following questions:

**Question:** Did any year experience a drop in the average sale price per square foot compared to the previous year?

**Answer:** YES, year 2011 experience a drop in the average sale price per square foot compare to year 2010.

**Question:** If so, did the gross rent increase or decrease during that year?

**Answer:** The gross rent increased that year (2011)

---

## Compare the Average Sale Prices by Neighborhood

For this part of the assignment, use interactive visualizations and widgets to explore the average sale price per square foot by neighborhood. To do so, complete the following steps:

1. Create a new DataFrame that groups the original DataFrame by year and neighborhood. Aggregate the results by the `mean` of the groups.

2. Filter out the “housing_units” column to create a DataFrame that includes only the `sale_price_sqr_foot` and `gross_rent` averages per year.

3. Create an interactive line plot with hvPlot that visualizes both `sale_price_sqr_foot` and `gross_rent`. Set the x-axis parameter to the year (`x="year"`). Use the `groupby` parameter to create an interactive widget for `neighborhood`.

4. Style and format the line plot to ensure a professionally styled visualization.

5. Note that your resulting plot should appear similar to the following image:

![A screenshot depicts an example of the resulting plot.](Images/pricing-info-by-neighborhood.png)

6. Use the interactive visualization to answer the following question:

    * For the Anza Vista neighborhood, is the average sale price per square foot for 2016 more or less than the price that’s listed for 2012? 


### Step 1: Create a new DataFrame that groups the original DataFrame by year and neighborhood. Aggregate the results by the `mean` of the groups.

In [65]:
# Group by year and neighborhood and then create a new dataframe of the mean values
prices_by_year_by_neighborhood = sfo_data_df.groupby(['year', 'neighborhood']).mean()

# Review the DataFrame
prices_by_year_by_neighborhood

sale_price_sqr_foot  housing_units  gross_rent
year neighborhood                                                          
2010 Alamo Square                     291.182945       372560.0      1239.0
     Anza Vista                       267.932583       372560.0      1239.0
     Bayview                          170.098665       372560.0      1239.0
     Buena Vista Park                 347.394919       372560.0      1239.0
     Central Richmond                 319.027623       372560.0      1239.0
...                                          ...            ...         ...
2016 Telegraph Hill                   903.049771       384242.0      4390.0
     Twin Peaks                       970.085470       384242.0      4390.0
     Van Ness/ Civic Center           552.602567       384242.0      4390.0
     Visitacion Valley                328.319007       384242.0      4390.0
     Westwood Park                    631.195426       384242.0      4390.0

[397 rows x 3 columns]

### Step 2: Filter out the “housing_units” column to create a DataFrame that includes only the `sale_price_sqr_foot` and `gross_rent` averages per year.

In [66]:
# Filter out the housing_units
prices_by_year_by_neighborhood = prices_by_year_by_neighborhood.drop(columns =["housing_units"])

# Review the first and last five rows of the DataFrame
display (prices_by_year_by_neighborhood.head())
display (prices_by_year_by_neighborhood.tail())

sale_price_sqr_foot  gross_rent
year neighborhood                                     
2010 Alamo Square               291.182945      1239.0
     Anza Vista                 267.932583      1239.0
     Bayview                    170.098665      1239.0
     Buena Vista Park           347.394919      1239.0
     Central Richmond           319.027623      1239.0

sale_price_sqr_foot  gross_rent
year neighborhood                                           
2016 Telegraph Hill                   903.049771      4390.0
     Twin Peaks                       970.085470      4390.0
     Van Ness/ Civic Center           552.602567      4390.0
     Visitacion Valley                328.319007      4390.0
     Westwood Park                    631.195426      4390.0

### Step 3: Create an interactive line plot with hvPlot that visualizes both `sale_price_sqr_foot` and `gross_rent`. Set the x-axis parameter to the year (`x="year"`). Use the `groupby` parameter to create an interactive widget for `neighborhood`.

### Step 4: Style and format the line plot to ensure a professionally styled visualization.

In [67]:
# Use hvplot to create an interactive line plot of the average price per square foot
# The plot should have a dropdown selector for the neighborhood
prices_by_year_by_neighborhood.hvplot(x ='year',
                                      y = ['sale_price_sqr_foot','gross_rent'],
                                      value_label='Gross Rent/Sale Price Per Square Foot',
                                      title='Sale Price per Square Foot and Average Gross Rent - 2010-2016 - by Neighborhood',
                                     groupby ="neighborhood")

:DynamicMap   [neighborhood]
   :NdOverlay   [Variable]
      :Curve   [year]   (Gross Rent/Sale Price Per Square Foot)

### Step 6: Use the interactive visualization to answer the following question:

**Question:** For the Anza Vista neighborhood, is the average sale price per square foot for 2016 more or less than the price that’s listed for 2012? 

**Answer:** the average sale price for 2016 is less than the price that’s listed for 2012

---

## Build an Interactive Neighborhood Map

For this part of the assignment, explore the geospatial relationships in the data by using interactive visualizations with hvPlot and GeoViews. To build your map, use the `sfo_data_df` DataFrame (created during the initial import), which includes the neighborhood location data with the average prices. To do all this, complete the following steps:

1. Read the `neighborhood_coordinates.csv` file from the `Resources` folder into the notebook, and create a DataFrame named `neighborhood_locations_df`. Be sure to set the `index_col` of the DataFrame as “Neighborhood”.

2. Using the original `sfo_data_df` Dataframe, create a DataFrame named `all_neighborhood_info_df` that groups the data by neighborhood. Aggregate the results by the `mean` of the group.

3. Review the two code cells that concatenate the `neighborhood_locations_df` DataFrame with the `all_neighborhood_info_df` DataFrame. Note that the first cell uses the [Pandas concat function](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.concat.html) to create a DataFrame named `all_neighborhoods_df`. The second cell cleans the data and sets the “Neighborhood” column. Be sure to run these cells to create the `all_neighborhoods_df` DataFrame, which you’ll need to create the geospatial visualization.

4. Using hvPlot with GeoViews enabled, create a `points` plot for the `all_neighborhoods_df` DataFrame. Be sure to do the following:

    * Set the `size` parameter to “sale_price_sqr_foot”.

    * Set the `color` parameter to “gross_rent”.

    * Set the `size_max` parameter to “25”.

    * Set the `zoom` parameter to “11”.

Note that your resulting plot should appear similar to the following image:

![A screenshot depicts an example of a scatter plot created with hvPlot and GeoViews.](Images/6-4-geoviews-plot.png)

5. Use the interactive map to answer the following question:

    * Which neighborhood has the highest gross rent, and which has the highest sale price per square foot?


### Step 1: Read the `neighborhood_coordinates.csv` file from the `Resources` folder into the notebook, and create a DataFrame named `neighborhood_locations_df`. Be sure to set the `index_col` of the DataFrame as “Neighborhood”.

In [68]:
# Load neighborhoods coordinates data
neighborhood_locations_df = pd.read_csv(Path("./Resources/neighborhoods_coordinates.csv"), index_col = ["Neighborhood"])

# Review the DataFrame
neighborhood_locations_df

Lat         Lon
Neighborhood                             
Alamo Square        37.791012 -122.402100
Anza Vista          37.779598 -122.443451
Bayview             37.734670 -122.401060
Bayview Heights     37.728740 -122.410980
Bernal Heights      37.728630 -122.443050
...                       ...         ...
West Portal         37.740260 -122.463880
Western Addition    37.792980 -122.435790
Westwood Highlands  37.734700 -122.456854
Westwood Park       37.734150 -122.457000
Yerba Buena         37.792980 -122.396360

[73 rows x 2 columns]

### Step 2: Using the original `sfo_data_df` Dataframe, create a DataFrame named `all_neighborhood_info_df` that groups the data by neighborhood. Aggregate the results by the `mean` of the group.

In [69]:
# Calculate the mean values for each neighborhood
all_neighborhood_info_df = sfo_data_df.groupby('neighborhood').mean()

# Review the resulting DataFrame
all_neighborhood_info_df

year  sale_price_sqr_foot  housing_units  \
neighborhood                                                          
Alamo Square        2013.000000           366.020712      378401.00   
Anza Vista          2013.333333           373.382198      379050.00   
Bayview             2012.000000           204.588623      376454.00   
Bayview Heights     2015.000000           590.792839      382295.00   
Bernal Heights      2013.500000           576.746488      379374.50   
...                         ...                  ...            ...   
West Portal         2012.250000           498.488485      376940.75   
Western Addition    2012.500000           307.562201      377427.50   
Westwood Highlands  2012.000000           533.703935      376454.00   
Westwood Park       2015.000000           687.087575      382295.00   
Yerba Buena         2012.500000           576.709848      377427.50   

                     gross_rent  
neighborhood                     
Alamo Square        2817.285714  
Anza Vista          3031.833333  
Bayview             2318.400000  
Bayview Heights     3739.000000  
Bernal Heights      3080.333333  
...                         ...  
West Portal         2515.500000  
Western Addition    2555.166667  
Westwood Highlands  2250.500000  
Westwood Park       3959.000000  
Yerba Buena         2555.166667  

[73 rows x 4 columns]

### Step 3: Review the two code cells that concatenate the `neighborhood_locations_df` DataFrame with the `all_neighborhood_info_df` DataFrame. 

Note that the first cell uses the [Pandas concat function](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.concat.html) to create a DataFrame named `all_neighborhoods_df`. 

The second cell cleans the data and sets the “Neighborhood” column. 

Be sure to run these cells to create the `all_neighborhoods_df` DataFrame, which you’ll need to create the geospatial visualization.

In [70]:
# Using the Pandas `concat` function, join the 
# neighborhood_locations_df and the all_neighborhood_info_df DataFrame
# The axis of the concatenation is "columns".
# The concat function will automatially combine columns with
# identical information, while keeping the additional columns.
all_neighborhoods_df = pd.concat(
    [neighborhood_locations_df, all_neighborhood_info_df], 
    axis="columns",
    sort=False
)

# Review the resulting DataFrame
display(all_neighborhoods_df.head())
display(all_neighborhoods_df.tail())


Lat         Lon         year  sale_price_sqr_foot  \
Alamo Square     37.791012 -122.402100  2013.000000           366.020712   
Anza Vista       37.779598 -122.443451  2013.333333           373.382198   
Bayview          37.734670 -122.401060  2012.000000           204.588623   
Bayview Heights  37.728740 -122.410980  2015.000000           590.792839   
Bernal Heights   37.728630 -122.443050          NaN                  NaN   

                 housing_units   gross_rent  
Alamo Square          378401.0  2817.285714  
Anza Vista            379050.0  3031.833333  
Bayview               376454.0  2318.400000  
Bayview Heights       382295.0  3739.000000  
Bernal Heights             NaN          NaN

Lat        Lon    year  sale_price_sqr_foot  \
Yerba Buena      37.79298 -122.39636  2012.5           576.709848   
Bernal Heights        NaN        NaN  2013.5           576.746488   
Downtown              NaN        NaN  2013.0           391.434378   
Ingleside             NaN        NaN  2012.5           367.895144   
Outer Richmond        NaN        NaN  2013.0           473.900773   

                 housing_units   gross_rent  
Yerba Buena           377427.5  2555.166667  
Bernal Heights        379374.5  3080.333333  
Downtown              378401.0  2817.285714  
Ingleside             377427.5  2509.000000  
Outer Richmond        378401.0  2817.285714

In [71]:
# Call the dropna function to remove any neighborhoods that do not have data
all_neighborhoods_df = all_neighborhoods_df.reset_index().dropna()

# Rename the "index" column as "Neighborhood" for use in the Visualization
all_neighborhoods_df = all_neighborhoods_df.rename(columns={'index' : 'Neighborhood'}).drop_duplicates()


# Review the resulting DataFrame
display(all_neighborhoods_df.head())
display(all_neighborhoods_df.tail())

Neighborhood        Lat         Lon         year  sale_price_sqr_foot  \
0      Alamo Square  37.791012 -122.402100  2013.000000           366.020712   
1        Anza Vista  37.779598 -122.443451  2013.333333           373.382198   
2           Bayview  37.734670 -122.401060  2012.000000           204.588623   
3   Bayview Heights  37.728740 -122.410980  2015.000000           590.792839   
5  Buena Vista Park  37.768160 -122.439330  2012.833333           452.680591   

   housing_units   gross_rent  
0       378401.0  2817.285714  
1       379050.0  3031.833333  
2       376454.0  2318.400000  
3       382295.0  3739.000000  
5       378076.5  2698.833333

Neighborhood       Lat         Lon     year  sale_price_sqr_foot  \
68         West Portal  37.74026 -122.463880  2012.25           498.488485   
69    Western Addition  37.79298 -122.435790  2012.50           307.562201   
70  Westwood Highlands  37.73470 -122.456854  2012.00           533.703935   
71       Westwood Park  37.73415 -122.457000  2015.00           687.087575   
72         Yerba Buena  37.79298 -122.396360  2012.50           576.709848   

    housing_units   gross_rent  
68      376940.75  2515.500000  
69      377427.50  2555.166667  
70      376454.00  2250.500000  
71      382295.00  3959.000000  
72      377427.50  2555.166667

In [72]:
# Filtering out the year columns to clean up the data

all_neighborhoods_df = all_neighborhoods_df.drop(columns = ['year'])

# Reviewing 
display(all_neighborhoods_df.head())
display(all_neighborhoods_df.tail())

Neighborhood        Lat         Lon  sale_price_sqr_foot  \
0      Alamo Square  37.791012 -122.402100           366.020712   
1        Anza Vista  37.779598 -122.443451           373.382198   
2           Bayview  37.734670 -122.401060           204.588623   
3   Bayview Heights  37.728740 -122.410980           590.792839   
5  Buena Vista Park  37.768160 -122.439330           452.680591   

   housing_units   gross_rent  
0       378401.0  2817.285714  
1       379050.0  3031.833333  
2       376454.0  2318.400000  
3       382295.0  3739.000000  
5       378076.5  2698.833333

Neighborhood       Lat         Lon  sale_price_sqr_foot  \
68         West Portal  37.74026 -122.463880           498.488485   
69    Western Addition  37.79298 -122.435790           307.562201   
70  Westwood Highlands  37.73470 -122.456854           533.703935   
71       Westwood Park  37.73415 -122.457000           687.087575   
72         Yerba Buena  37.79298 -122.396360           576.709848   

    housing_units   gross_rent  
68      376940.75  2515.500000  
69      377427.50  2555.166667  
70      376454.00  2250.500000  
71      382295.00  3959.000000  
72      377427.50  2555.166667

### Step 4: Using hvPlot with GeoViews enabled, create a `points` plot for the `all_neighborhoods_df` DataFrame. Be sure to do the following:

* Set the `geo` parameter to True.
* Set the `size` parameter to “sale_price_sqr_foot”.
* Set the `color` parameter to “gross_rent”.
* Set the `frame_width` parameter to 700.
* Set the `frame_height` parameter to 500.
* Include a descriptive title.

In [73]:
# Create a plot to analyze neighborhood info
all_neighborhoods_df.hvplot.points('Lon',
                                   'Lat',
                                   geo=True,
                                   size='sale_price_sqr_foot',
                                   color='gross_rent',
                                   frame_width= 700,
                                   frame_height=500,
                                   tiles='OSM',
                                   hover_cols='Neighborhood'
                                  )

:Overlay
   .Tiles.I  :Tiles   [x,y]
   .Points.I :Points   [Lon,Lat]   (gross_rent,sale_price_sqr_foot,Neighborhood)

### Step 5: Use the interactive map to answer the following question:

**Question:** Which neighborhood has the highest gross rent, and which has the highest sale price per square foot?

**Answer:** Westwood Park is the neighborhood that has the highest gross rent estimated at: 3959.0, and Union Square District is the neighborhood that has the highest sale price per square foot estimated at: 903.99 



In [74]:
# We can use the df to display the neighborhood with the highest gross rent
highest_gross_rent_neighborhood = all_neighborhoods_df.sort_values('gross_rent').tail(1)
highest_gross_rent_neighborhood

Neighborhood       Lat      Lon  sale_price_sqr_foot  housing_units  \
71  Westwood Park  37.73415 -122.457           687.087575       382295.0   

    gross_rent  
71      3959.0

In [43]:
"""
# Other way to display the neighborhood that has the highest gross rent
    # first, we look for highest gross rent using .max 
highest_gross_rent = all_neighborhood_info_df['gross_rent'].max()
highest_gross_rent

    # then, Neighborhood of the highest gross rent (neighborhood being the index in all_neighborhood_info_df) 
    # so we use .idmax to call the index of the .max
highest_gross_rent_neighborhood = all_neighborhood_info_df['gross_rent'].idxmax()
highest_gross_rent_neighborhood

print(f'{highest_gross_rent_neighborhood} is the neighborhood that has the highest gross rent estimated at: ${highest_gross_rent} ')
"""

Westwood Park is the neighborhood that has the highest gross rent estimated at: $3959.0 


In [75]:
# the neighborhood that has the highest sale price per square foot
# We can use the df to display the neighborhood with the highest gross rent
highest_sale_price_per_foot_neighborhood = all_neighborhoods_df.sort_values('sale_price_sqr_foot').tail(1)
highest_sale_price_per_foot_neighborhood

Neighborhood       Lat       Lon  sale_price_sqr_foot  \
65  Union Square District  37.79101 -122.4021           903.993258   

    housing_units   gross_rent  
65       377427.5  2555.166667

In [44]:
"""
# Other option: The neighborhood that has the highest sale price per square foot

highest_sale_price_per_foot = all_neighborhood_info_df['sale_price_sqr_foot'].max()
highest_sale_price_per_foot

# then, Neighborhood of the highest sale price per square foot (neighborhood being the index in all_neighborhood_info_df) 
    # so we use .idmax to call the index of the .max
highest_sale_price_per_foot_neighborhood = all_neighborhood_info_df['sale_price_sqr_foot'].idxmax()
highest_sale_price_per_foot_neighborhood

print(f'{highest_sale_price_per_foot_neighborhood} is the neighborhood that has the highest sale price per square foot estimated at: ${highest_sale_price_per_foot: .2f} ')
"""

Union Square District is the neighborhood that has the highest sale price per square foot estimated at: $ 903.99 


In [21]:
# Create a plot to analyze neighborhood info
all_neighborhoods_df.hvplot.points('Lon',
                                   'Lat',
                                   geo=True,
                                   size='sale_price_sqr_foot',
                                   color='Neighborhood',
                                   scale = 1.0,
                                   frame_width= 700,
                                   frame_height=500,
                                   tiles='OSM',
                                   hover_cols='Neighborhood'
                                  )

:Overlay
   .Tiles.I  :Tiles   [x,y]
   .Points.I :Points   [Lon,Lat]   (Neighborhood,sale_price_sqr_foot)

## Compose Your Data Story

Based on the visualizations that you have created, compose a data story that synthesizes your analysis by answering the following questions:

**Question:**  How does the trend in rental income growth compare to the trend in sales prices? Does this same trend hold true for all the neighborhoods across San Francisco?

**Answer:** # YOUR ANSWER HERE

In [76]:
# Create a visual aggregation explore the sale_price_sqr_foot per neighborhood

sale_price_plot = all_neighborhoods_df.hvplot.bar(x= "Neighborhood",
                                 y= "sale_price_sqr_foot",
                                 label= "sale_price_sqr_foot",
                                 rot= 90,
                                ).opts(yformatter='%.0f')
sale_price_plot

:Bars   [Neighborhood]   (sale_price_sqr_foot)

In [77]:
# Create a visual aggregation explore the sale_price_sqr_foot per neighborhood

gross_rent_plot = all_neighborhoods_df.hvplot.bar(x= "Neighborhood",
                                 y= "gross_rent",
                                 label= "gross rent",
                                 rot= 90,
                                ).opts(yformatter='%.0f')
gross_rent_plot

:Bars   [Neighborhood]   (gross_rent)

In [78]:
overlay_plots = gross_rent_plot * sale_price_plot
overlay_plots.opts(
    height= 500,
    width=1200,
    xlabel="Neighborhood",
    ylabel="Amount in US Dollars",
    title ="Comparison Sale Price per square foot / Gross Rent per neighborhood in San Francisco from 2010 to 2016"
)

:Overlay
   .Bars.Gross_rent          :Bars   [Neighborhood]   (gross_rent)
   .Bars.Sale_price_sqr_foot :Bars   [Neighborhood]   (sale_price_sqr_foot)

**Question:** What insights can you share with your company about the potential one-click, buy-and-rent strategy that they're pursuing? Do neighborhoods exist that you would suggest for investment, and why?

**Answer:** # For on-click, Buy-and-Rent Strategy, the. best case scenario would a neighborhood that offer the lowest price per square foot and with the highest gross rent. Buy low and Rent hight.
Silver Terrace would be my first choice of investment.
Visitacion Valley in second position.

In [95]:
# Let fetch the 10 highest rent and the 
ten_highest_rent = all_neighborhoods_df.sort_values('gross_rent').tail(10)
ten_highest_rent

Neighborhood        Lat         Lon  sale_price_sqr_foot  \
47      Outer Mission  37.722800 -122.438690           242.370952   
16          Excelsior  37.728740 -122.410980           388.765927   
1          Anza Vista  37.779598 -122.443451           373.382198   
41    Mission Terrace  37.728630 -122.443050           523.466201   
28     Inner Parkside  37.749610 -122.489990           519.385604   
36     Merced Heights  37.719930 -122.465950           788.844818   
59     Silver Terrace  37.734670 -122.401060           170.292549   
67  Visitacion Valley  37.728740 -122.410980           301.466180   
3     Bayview Heights  37.728740 -122.410980           590.792839   
71      Westwood Park  37.734150 -122.457000           687.087575   

    housing_units   gross_rent  
47      379374.50  2995.750000  
16      379050.00  3031.833333  
1       379050.00  3031.833333  
41      379569.20  3173.400000  
28      379861.25  3224.000000  
36      380348.00  3414.000000  
59      380348.00  3528.000000  
67      381321.50  3657.000000  
3       382295.00  3739.000000  
71      382295.00  3959.000000

In [96]:
# Let determine the ten lowest sale price per foot square 
ten_highest_sale_price = all_neighborhoods_df.sort_values('sale_price_sqr_foot').head(10)
ten_highest_sale_price

Neighborhood       Lat        Lon  sale_price_sqr_foot  \
59     Silver Terrace  37.73467 -122.40106           170.292549   
24      Hunters Point  37.72551 -122.37178           170.624920   
2             Bayview  37.73467 -122.40106           204.588623   
47      Outer Mission  37.72280 -122.43869           242.370952   
67  Visitacion Valley  37.72874 -122.41098           301.466180   
11      Croker Amazon  37.72280 -122.43869           303.004184   
69   Western Addition  37.79298 -122.43579           307.562201   
19      Forest Knolls  37.75706 -122.45509           321.840837   
55            Portola  37.73467 -122.40106           327.113925   
46          Oceanview  37.71993 -122.46595           330.097385   

    housing_units   gross_rent  
59       380348.0  3528.000000  
24       377427.5  2489.000000  
2        376454.0  2318.400000  
47       379374.5  2995.750000  
67       381321.5  3657.000000  
11       378076.5  2698.833333  
69       377427.5  2555.166667  
19       374507.0  1781.500000  
55       376454.0  2318.400000  
46       377103.0  2434.000000

In [97]:
#inner join to get the five Best Neighborhood of san Francisco to invest in, sorted by sale price per sqr ft
 
inner_join_df= pd.merge(ten_highest_rent, ten_highest_sale_price, on='Neighborhood', how='inner')
filter_inner_join_df = inner_join_df[['Neighborhood', 'sale_price_sqr_foot_x', 'gross_rent_x', 'Lat_x', 'Lon_x']]
ten_best_neighborhoods_for_investment = filter_inner_join_df.sort_values('sale_price_sqr_foot_x').head(10)
ten_best_neighborhoods_for_investment


Neighborhood  sale_price_sqr_foot_x  gross_rent_x     Lat_x      Lon_x
1     Silver Terrace             170.292549       3528.00  37.73467 -122.40106
0      Outer Mission             242.370952       2995.75  37.72280 -122.43869
2  Visitacion Valley             301.466180       3657.00  37.72874 -122.41098

In [100]:

gross_rent_x_plot = ten_best_neighborhoods_for_investment.hvplot.bar(x= "Neighborhood",
                                                                     y= "gross_rent_x",
                                                                     label= "gross_rent_x",
                                                                     rot= 90
                                                                    ).opts(yformatter='%.0f')


sale_price_x_plot = ten_best_neighborhoods_for_investment.hvplot.bar(x= "Neighborhood",
                                                                     y= "sale_price_sqr_foot_x",
                                                                     label= "sale_price_sqr_foot_x",
                                                                     rot= 90
                                                                    ).opts(yformatter='%.0f')

ten_best_neighborhoods_for_investment_plot = gross_rent_x_plot * sale_price_x_plot
ten_best_neighborhoods_for_investment_plot.opts(height= 500,
                                                 width=500,
                                                 xlabel="Neighborhood",
                                                 ylabel="Amount in US Dollars",
                                                 title ="Comparison Sale Price per square foot / Gross Rent of the 10 best neighborhoods for investment \n in real Estates in San Francisco from 2010 to 2016"
                                                )

:Overlay
   .Bars.Gross_rent_x          :Bars   [Neighborhood]   (gross_rent_x)
   .Bars.Sale_price_sqr_foot_x :Bars   [Neighborhood]   (sale_price_sqr_foot_x)

In [101]:
# Create a plot to analyze the 10 Best neighborhoods 
ten_best_neighborhoods_for_investment.hvplot.points('Lon_x',
                                   'Lat_x',
                                   geo=True,
                                   size='sale_price_sqr_foot_x',
                                   color='Neighborhood',
                                   scale = 0.9,
                                   frame_width= 700,
                                   frame_height=500,
                                   tiles='OSM',
                                   hover_cols='Neighborhood'
                                  )

:Overlay
   .Tiles.I  :Tiles   [x,y]
   .Points.I :Points   [Lon_x,Lat_x]   (Neighborhood,sale_price_sqr_foot_x)